config/routes.rb
Rails.application.routes.draw do

resources :restaurants, only: [:index, :new, :create, :show] do
   resources :reviews, only: [:new, :create]
 end

 namespace :admin do
    resources :restaurants
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :find_restaurant, only: [:show, :edit, :update]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def show
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    # New Review
    # Add the info from the user to the review
    @review = Review.new(review_params)
    # Link the review to the restaurant
    @review.restaurant = @restaurant
    # Save the review
    @review.save
    # Redirect to restaurant#show
    redirect_to @restaurant
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <%= simple_form_for @restaurant do |f| %>
    <% if @restaurant.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>

    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/_restaurant_list.html.erb
<% restaurants.each do |restaurant| %>
<div class="restaurant">
  <h5><%= restaurant.name %> </h5>

  <p><%= link_to "More details", restaurant_path(restaurant) %></p>
</div>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<p><%= link_to "+ Add Restaurant", new_restaurant_path %></p>
<%= render 'restaurant_list', restaurants: @restaurants %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Category: <%= @restaurant.category %></p>
<p>Phone number: <%= @restaurant.phone_number %></p>
<p>Address: <%= @restaurant.address %></p>


<h3>Review</h3>

<% @restaurant.reviews.each do |review| %>
<div>
  <%= review.rating %>
  <%= review.content %>
</div>
<% end %>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant)%>
<%= link_to "Go back to list", restaurants_path %>

app/views/reviews/new.html.erb
<h1>Add a review for <%= @restaurant.name %></h1>

<div class="container">
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>
</div>